#!/bin/bash

wget https://github.com/dikiy4eburator/arch-helpers/blob/master/1-install-prepare
wget https://github.com/dikiy4eburator/arch-helpers/blob/master/2-system-config
wget https://github.com/dikiy4eburator/arch-helpers/blob/master/3-install-gui

