#!/bin/bash

#loadkeys de-latin1
clear
lsblk
echo
read -p "Bitte Festplatte für die installation angeben: " HDD
cgdisk /dev/$HDD

BOOT_HD="${HDD}1"
SWAP_HD="${HDD}2"
ROOT_HD="${HDD}3"
HOME_HD="${HDD}4"

# formating partitions
mkfs.fat -F32 /dev/$BOOT_HD
mkswap /dev/$SWAP_HD
mkfs.ext4 /dev/$ROOT_HD
mkfs.ext4 /dev/$HOME_HD

# Mounting partitions
mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
mkdir /mnt/boot
mkdir /mnt/boot/efi
mount /dev/$BOOT_HD /mnt/boot/efi
mkdir /mnt/home
mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
swapon /dev/$SWAP_HD

# Install base pacages
pacstrap -i /mnt base base-devel linux-headers grub os-prober efibootmgr acpid dbus

# Generate fstab
genfstab -U -p /mnt >> /mnt/etc/fstab

curl -o /mnt/home/2 https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/2-configuration
curl -o /mnt/home/3 https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/3-gui-conf

arch-chroot /mnt
