#!/bin/bash

#loadkeys de-latin1
clear
lsblk
echo
read -p "Bitte Festplatte für die installation angeben: " HDD
cgdisk /dev/$HDD

BOOT_HD="${HDD}p1"
SWAP_HD="${HDD}p2"
ROOT_HD="${HDD}p3"
HOME_HD="${HDD}p4"

# formating partitions
mkfs.fat -F32 /dev/$BOOT_HD
mkswap /dev/$SWAP_HD
mkfs.ext4 /dev/$ROOT_HD
mkfs.ext4 /dev/$HOME_HD

# Mounting partitions
mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
mkdir /mnt/boot
mkdir /mnt/boot/efi
mount /dev/$BOOT_HD /mnt/boot/efi
mkdir /mnt/home
mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
swapon /dev/$SWAP_HD

# Install base pacages
pacstrap -i /mnt base base-devel linux-headers grub os-prober efibootmgr acpid dbus

# Generate fstab
genfstab -U -p /mnt >> /mnt/etc/fstab

curl -o /mnt/home/2-configuration https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/2-configuration
curl -o /mnt/home/3-gui-conf https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/3-gui-conf

arch-chroot /mnt

#/////////////////////////////////////////////////////////////////

# --------------------------------------------------
# "PARTITIONIEREN WENN BENÖTIGT"
# cgdisk
#
# efi = ef00
# swap = 8200
# linux = 8300
 
# "FORMATIEREN WENN BENÖTIGT"
# z.B :
#    mkfs.fat -F32 /dev/…
#    mkfs.btrfs /dev/...
#    mkswap /dev/...
#    mkfs.ext4 /dev/...
# 
# -------------------------------------------------
# mount -o umask=0077 /dev/…  /mnt/boot
# mount -o defaults,noatime,discard /dev/… /mnt
# mount -o defaults,noatime,discard /dev/… /mnt/home
# swapon /dev/...
# --------------------------------------------------------------



