#!/bin/sh

# //////////////////////////////////////////////////////////////////////////////
# //////////////////    FUNKTION DEFENITIONS   /////////////////////////////////
# //////////////////////////////////////////////////////////////////////////////


# ////////////////////    EFI MODE HDD PREPARATION    /////////////////////////////////////

function f_install_efi() {
  case $HDD in
    nvme*)
      f_defineHdPattern_nvme_efi
      ;;

    sd*)
      f_defineHdPattern_sata_efi
      ;;

    *)
      echo "HDD eingabe unbekant"
      exit
      ;;
  esac
  
f_format_efi
f_mount_efi
}

function f_defineHdPattern_sata_efi() {
  case $EXTRAHOME in
    ja )
      BOOT_HD="${HDD}1"
      SWAP_HD="${HDD}2"
      ROOT_HD="${HDD}3"
      HOME_HD="${HDD}4"
      ;;

    nein )
      BOOT_HD="${HDD}1"
      SWAP_HD="${HDD}2"
      ROOT_HD="${HDD}3"
      ;;
  esac
}

function f_defineHdPattern_nvme_efi() {
  case $EXTRAHOME in
    ja )
      BOOT_HD="${HDD}p1"
      SWAP_HD="${HDD}p2"
      ROOT_HD="${HDD}p3"
      HOME_HD="${HDD}p4"
      ;;

    nein )
      BOOT_HD="${HDD}p1"
      SWAP_HD="${HDD}p2"
      ROOT_HD="${HDD}p3"
      ;;
  esac
}

function f_format_efi() {
  case $EXTRAHOME in
    ja )
      # formating partitions
      mkfs.fat -F32 /dev/$BOOT_HD
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      mkfs.ext4 /dev/$HOME_HD
      ;;

    nein )
      # formating partitions
      mkfs.fat -F32 /dev/$BOOT_HD
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      ;;
  esac
}

function f_mount_efi() {
  case $EXTRAHOME in
    ja )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
      mkdir /mnt/boot
      mkdir /mnt/boot/efi
      mount /dev/$BOOT_HD /mnt/boot/efi
      mkdir /mnt/home
      mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
      swapon /dev/$SWAP_HD
      ;;

    nein )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
      mkdir /mnt/boot
      mkdir /mnt/boot/efi
      mount /dev/$BOOT_HD /mnt/boot/efi
      swapon /dev/$SWAP_HD
      ;;
  esac
}
# ////////////////////    EFI PREP  END  /////////////////////////////////////





# ////////////////////   LEGACY PREP   ///////////////////////////////////////


function f_install_legacy() {
  case $HDD in
    nvme*)
     f_defineHdPattern_nvme_legacy
      ;;

    sd*)
     f_defineHdPattern_sata_legacy
     ;;

    *)
      echo "HDD eingabe unbekant"
      exit
     ;;
  esac
f_format_legacy
f_mount_legacy
}

function f_defineHdPattern_sata_legacy() {
  case $EXTRAHOME in
    ja )
      BOOT_HD="${HDD}1"
      SWAP_HD="${HDD}2"
      ROOT_HD="${HDD}3"
      HOME_HD="${HDD}4"
      ;;

    nein )
      BOOT_HD="${HDD}1"
      SWAP_HD="${HDD}2"
      ROOT_HD="${HDD}3"
      ;;
  esac
}

function f_defineHdPattern_nvme_legacy() {
  case $EXTRAHOME in
    ja )
      BOOT_HD="${HDD}p1"
      SWAP_HD="${HDD}p2"
      ROOT_HD="${HDD}p3"
      HOME_HD="${HDD}p4"
      ;;

    nein )
      BOOT_HD="${HDD}p1"
      SWAP_HD="${HDD}p2"
      ROOT_HD="${HDD}p3"
      ;;
  esac
}

function f_format_legacy() {
  case $EXTRAHOME in
    ja )
      # formating partitions
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      mkfs.ext4 /dev/$HOME_HD
      ;;

    nein )
      # formating partitions
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      ;;
  esac
}

function f_mount_legacy() {
  case $EXTRAHOME in
    ja )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
      mkdir /mnt/boot
      mount /dev/$BOOT_HD /mnt/boot
      mkdir /mnt/home
      mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
      swapon /dev/$SWAP_HD
      ;;

    nein )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
      mkdir /mnt/boot
      mount /dev/$BOOT_HD /mnt/boot
      swapon /dev/$SWAP_HD
      ;;
  esac
}

# ////////////////////   LEGACY PREP  END  /////////////////////////////////////







# //////////////////////////////////////////////////////////////////////////////
# //////////////////    START INSTALATION   ////////////////////////////////////
# //////////////////////////////////////////////////////////////////////////////

# Welkom Screan
clear
echo "#################################################"
echo "# Wilkommen beim Arch installations skript"
echo "#################################################"
echo "#"
echo "# Bitte beantworten Sie einige Fragen zu der Systemconfiguration"
echo "#"
read -p "#     Drücken Sie Enter zum fortfahren"
echo "#"
echo

# Home partition Screan
clear
echo "#################################################"
echo "#"
echo "# Mochten Sie eine extra HOME Partition haben? (ja/nein)"
read -p "# >> " EXTRAHOME
echo "#"

# HDD select Screan
clear
echo "#################################################"
echo
echo
lsblk -o NAME,SIZE,MODEL,TYPE | grep disk
echo
echo
echo "# Welche Festplatte, von den oben gezeigten,"
echo "# soll für die Installation benutzt werden?"
echo "#     (z.B. sda, nvme0n1 etc.)"
echo "#"
echo "#          !!! ACHTUNG  !!!"
echo "#   die Festplatte wird komplet gelöscht"
echo "#"
read -p "# >> " HDD
echo "#"

# Show Partitioning info depending on boot mode
if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    clear
    echo "#################################################"
    echo "# Im folgenden wird das Programm cgdisk gestartet"
    echo "# Bitte erstellen Sie die Partitione in der folgenden Ordnung:"
    echo "#"
    echo "#  1. EFI ca. 100-256 Mb ( code: ef00 )"
    echo "#  2. SWAP Gröse nach eigenem Ermessen ca. 4-8 Gb ( code: 8200 )"
    echo "#"
    echo "#     Wenn Sie keine extra HOME Partition wollen"
    echo "#     Könne Sie den restlichen Speicher der ROOT Partition zweisen"
    echo "#     Ansonsten: "
    echo "#"
    echo "#  3. ROOT ca. 20-40 Gb ( code: 8300 )"
    echo "#  4. HOME rest des Speichers ( code: 8300 )"
    echo
    echo
  else
    clear
    echo "#################################################"
    echo "# Im folgenden wird das Programm cgdisk gestartet"
    echo "# Bitte erstellen Sie die Partitione in der folgenden Ordnung:"
    echo "#"
    echo "#  1. boot ca. 5 Mb ( code: ef02)"
    echo "#  2. SWAP Gröse nach eigenem Ermessen ca. 4-8 Gb ( code: 8200 )"
    echo "#"
    echo "#     Wenn Sie keine extra HOME Partition wollen"
    echo "#     Könne Sie den restlichen Speicher der ROOT Partition zweisen"
    echo "#     Ansonsten: "
    echo "#"
    echo "#  3. ROOT ca. 20-40 Gb ( code: 8300 )"
    echo "#  4. HOME rest des Speichers ( code: 8300 )"
    echo
    echo
fi

read -p "#        Drücken Sie Enter zum fortfahren"




# Start cgdisk
cgdisk /dev/$HDD

# Start HDD preparation
if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    f_install_efi
  else
    f_install_legacy
fi

# Install base pacages
pacstrap -i /mnt base base-devel linux-headers grub os-prober efibootmgr acpid dbus fish

# Generate fstab
genfstab -U -p /mnt >> /mnt/etc/fstab

# Download script 2 and 3
curl -o /mnt/home/2 https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/2-config
curl -o /mnt/home/3 https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/3-gui-conf

# Save HDD name for script 2
echo "$HDD" > /mnt/home/hdd

# clear
echo "#################################################"
echo "# Bitte in das /home verzeichniss der neuen installation weckseln"
echo "# und das skript 2 starten"
echo "#"
read -p "#        Drücken Sie Enter zum fortfahren"

# Chroot in to the new system
arch-chroot /mnt

exit












# //// NEED TESTING ///////////
# source /path/to/the/include/My_Other_Other_Script.sh   # explicit PATH
