#!/bin/sh

curl -o 1-prep-efi https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/1-prep-efi
curl -o 1-prep-legacy https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/1-prep-legacy

# source ~/root/1-prep-efi
# source ~/root/1-prep-legacy

clear
echo "#################################################"
echo " Wilkommen beim Arch EFI installations skript"
echo "#################################################"
echo
echo "Bitte beantworten Sie einige Fragen zu der Systemconfiguration"
echo
echo "Mochten Sie eine extra HOME Partition haben? (ja/nein)"
read -p ">> " EXTRAHOME
clear
echo
echo
lsblk -o NAME,SIZE,TYPE | grep disk
echo
echo
echo "Welche Festplatte, von den oben gezeigten,"
echo "soll für die Installation benutzt werden? (z.B. sda, nvme0n1 etc.) "
echo
read -p ">> " HDD
echo "$HDD" > /mnt/home/hdd
echo

# Show info depending on boot mode
if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    clear
    echo "Im folgenden wird das Programm cgdisk gestartet"
    echo "Bitte erstellen Sie die Partitione in der folgenden Ordnung:"
    echo
    echo "  1. EFI ca. 100-256 Mb ( code: ef00 )"
    echo "  2. SWAP Gröse nach eigenem Ermessen ca. 4-8 Gb ( code: 8200 )"
    echo
    echo "     Wenn Sie keine extra HOME Partition wollen"
    echo "     Könne Sie den restlichen Speicher der ROOT Partition zweisen"
    echo "     Ansonsten: "
    echo
    echo "  3. ROOT ca. 20-40 Gb ( code: 8300 )"
    echo "  4. HOME rest des Speichers ( code: 8300 )"
    echo
    echo
  else
    clear
    echo "Im folgenden wird das Programm cgdisk gestartet"
    echo "Bitte erstellen Sie die Partitione in der folgenden Ordnung:"
    echo
    echo "  1. boot ca. 5 Mb mit (ef02)"
    echo "  2. SWAP Gröse nach eigenem Ermessen ca. 4-8 Gb ( code: 8200 )"
    echo
    echo "     Wenn Sie keine extra HOME Partition wollen"
    echo "     Könne Sie den restlichen Speicher der ROOT Partition zweisen"
    echo "     Ansonsten: "
    echo
    echo "  3. ROOT ca. 20-40 Gb ( code: 8300 )"
    echo "  4. HOME rest des Speichers ( code: 8300 )"
    echo
    echo
fi

read -p "Drücken Sie Enter zum fortfahren"

cgdisk /dev/$HDD


if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    1-prep-efi
  else
    1-prep-legacy
fi

# Install base pacages
pacstrap -i /mnt base base-devel linux-headers grub os-prober efibootmgr acpid dbus fish

# Generate fstab
genfstab -U -p /mnt >> /mnt/etc/fstab

curl -o /mnt/home/2 https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/2-config
curl -o /mnt/home/3 https://raw.githubusercontent.com/dikiy4eburator/arch-helpers/master/3-gui-conf


clear
echo "##################################"
echo "Bitte in das /home verzeichniss der neuen installation weckseln"
echo "und das skript 2 starten"
echo "##################################"

arch-chroot /mnt

exit
