#!/bin/sh


function f_install_legacy() {
  case $HDD in
    nvme*)
    f_defineHdPattern_nvme_legacy
    ;;

    sd*)
    f_defineHdPattern_sata_legacy
    ;;

    *)
    echo "HDD eingabe unbekant"
    exit
    ;;
esac
f_format_legacy
f_mount_legacy
}

function f_defineHdPattern_sata_legacy() {
  case $EXTRAHOME in
    ja )
      BOOT_HD="${HDD}1"
      SWAP_HD="${HDD}2"
      ROOT_HD="${HDD}3"
      HOME_HD="${HDD}4"
      ;;

    nein )
      BOOT_HD="${HDD}1"
      SWAP_HD="${HDD}2"
      ROOT_HD="${HDD}3"
      ;;
  esac
}

function f_defineHdPattern_nvme_legacy() {
  case $EXTRAHOME in
    ja )
      BOOT_HD="${HDD}p1"
      SWAP_HD="${HDD}p2"
      ROOT_HD="${HDD}p3"
      HOME_HD="${HDD}p4"
      ;;

    nein )
      BOOT_HD="${HDD}p1"
      SWAP_HD="${HDD}p2"
      ROOT_HD="${HDD}p3"
      ;;
  esac
}

function f_format_legacy() {
  case $EXTRAHOME in
    ja )
      # formating partitions
      # mkfs.ext2 /dev/$BOOT_HD
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      mkfs.ext4 /dev/$HOME_HD
      ;;

    nein )
      # formating partitions
      # mkfs.ext2 /dev/$BOOT_HD
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      ;;
  esac
}

function f_mount_legacy() {
  case $EXTRAHOME in
    ja )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
      mkdir /mnt/boot
      mount /dev/$BOOT_HD /mnt/boot
      mkdir /mnt/home
      mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
      swapon /dev/$SWAP_HD
      ;;

    nein )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
      mkdir /mnt/boot
      mount /dev/$BOOT_HD /mnt/boot
      swapon /dev/$SWAP_HD
      ;;
  esac
}
