#!/bin/bash

# --------------------------------------------------
# "PARTITIONIEREN WENN BENÖTIGT"
# cgdisk
#
# efi = ef00
# swap = 8200
# linux = 8300
 
# "FORMATIEREN WENN BENÖTIGT"
# z.B :
#    mkfs.fat -F32 /dev/…
#    mkfs.btrfs /dev/...
#    mkswap /dev/...
#    mkfs.ext4 /dev/...
# 
# -------------------------------------------------
# mount -o umask=0077 /dev/…  /mnt/boot
# mount -o defaults,noatime,discard /dev/… /mnt
# mount -o defaults,noatime,discard /dev/… /mnt/home
# swapon /dev/...
# --------------------------------------------------------------

#loadkeys de-latin1

#read -p "Bitte Festplatte angeben: " HDD
#BOOT_HD="${HDD}1"
#ROOT_HD="${HDD}3"
#SWAP_HD="${HDD}2"

# formating partitions
#mkfs.fat -F32 /dev/$BOOT_HD
#mkswap /dev/$SWAP_HD
#mkfs.ext4 /dev/$ROOT_HD

# Mounting partitions
#mount /dev/$ROOT_HD /mnt
#mkdir /mnt/boot
#mkdir /mnt/boot/efi
#mount /dev/$BOOT_HD /mnt/boot/efi
#swapon /dev/$SWAP_HD

# Install base pacages
pacstrap -i /mnt base base-devel grub os-prober efibootmgr linux-headers xorg-server xorg-xinit lightdm lightdm-gtk-greeter acpid ntp dbus avahi networkmanager network-manager-applet nm-connection-editor pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol xfce4-appfinder caja mate-terminal urxvt chromium qt5 vlc mpv audacious noto-fonts arc-gtk-theme arc-icon-theme hunspell-de compton rofi neofetch nitrogen ranger polkit-gnome

# Generate fstab
genfstab -U -p /mnt  >> /mnt/etc/fstab
 
arch-chroot /mnt

