#!/bin/bash

clear
echo
echo "############################################"
echo
echo "1. virtualbox"
echo "2. Nvidia"
echo "3. ATI (xf86-video-ati basis Treiber)"
echo "4. Intel (xf86-video-intel basis Treiber)"
echo "5. VESA (xf86-video-vesa basis Treiber für den Notfall)"
echo
echo "############################################"
echo "Bitte wählen Sie ihren Grafiktreiber (1-5)"
echo
read -p " >> " GR
echo
case $GR in
  1 )
    pacman -S --noconfirm virtualbox-guest-dkms
    ;;
  2 )
    pacman -S --noconfirm nvidia
    ;;
  3 )
    pacman -S --noconfirm xf86-video-ati
    ;;
  4 )
    pacman -S --noconfirm xf86-video-intel
    ;;
  5)
    pacman -S --noconfirm xf86-video-vesa
    ;;
  * )
    echo "falsche eingabe"
    exit
esac

clear
echo "###################"
echo "# INSTALL PACAGES #"
echo "###################"
echo

#Install Network pakages
pacman -S --noconfirm avahi networkmanager network-manager-applet nm-connection-editor ntp

#Install Audio pakages
pacman -S --noconfirm pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol flac volumeicon audacious

#Install Video pakages
pacman -S --noconfirm xf86-input-keyboard xorg-server xorg-xinit compton ffmpeg vlc mpv

#Install GUI pakages
pacman -S --noconfirm i3blocks i3lock i3status lightdm lightdm-gtk-greeter

#Install Additional apps
pacman -S --noconfirm polkit-gnome xfce4-appfinder ranger git htop nitrogen
pacman -S --noconfirm chromium atom rofi conky dunst urxvt-perls hunspell-de darktable gimp
pacman -S --noconfirm nemo nemo-fileroller

#Install Themes
pacman -S --noconfirm lxappearance-gtk3 arc-gtk-theme arc-icon-theme archlinux-wallpaper

#Install fonts
pacman -S --noconfirm gnome-font-viewer noto-fonts awesome-terminal-fonts

clear
echo "################"
echo "# START CONFIG #"
echo "################"
echo
echo

# Set hostname
clear
echo "################"
echo "# Set Hostname #"
echo "################"
echo
read -p "Bitte Hostname eingeben: " HOSTX
echo $HOSTX >> /etc/hostname

clear
echo "################"
echo "# Set Locale   #"
echo "################"
echo

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
clear
echo "################"
echo "# Set ROOT PW  #"
echo "################"
echo
echo "Bitte Password für ROOT eingeben"
echo
passwd
echo
echo

# Set user
clear
echo "#################"
echo "# Set new USER  #"
echo "#################"
echo
read -p "Bitte neuen Benutzer Namen eingeben: " US
echo
echo "Generire Benutzer $US"
echo
useradd -m -g users -G wheel,video,audio,network -s /usr/bin/fish $US
echo "Bitte Password für $US eingeben"
passwd $US
echo
echo "Gebe $US ROOT rechte"
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#start system daemons
clear
echo "#################"
echo "# Start Daemons #"
echo "#################"
echo
systemctl enable acpid
systemctl enable ntpd
systemctl enable avahi-daemon
systemctl enable NetworkManager

# install grub
clear
echo "#################"
echo "# Setup GRUB    #"
echo "#################"
echo
grub-install --efi-directory=/boot/efi --bootloader-id=Arch
grub-mkconfig -o /boot/grub/grub.cfg

clear
echo "##################################"
echo "#### REBOOT AND LOGIN AS USER ####"
echo "#### then start script nr. 3  ####"
echo "##################################"

exit
