#!/bin/bash

clear
echo "###################"
echo "# INSTALL PACAGES #"
echo "###################"
echo 
echo 

#Install Network pakages
pacman -S --noconfirm avahi networkmanager network-manager-applet nm-connection-editor ntp

#Install Audio pakages
pacman -S --noconfirm pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol flac volumeicon audacious

#Install Video pakages
pacman -S --noconfirm xf86-input-keyboard xorg-server xorg-xinit compton ffmpeg vlc mpv virtualbox-guest-dkms nvidia

#Install GUI pakages
pacman -S --noconfirm i3blocks i3lock i3status lightdm lightdm-gtk-greeter

#Install Additional apps
pacman -S --noconfirm polkit-gnome xfce4-appfinder ranger git htop zsh zsh-completions zsh-syntax-highlighting nitrogen
pacman -S --noconfirm firefox firefox-i18n-de atom rofi conky dunst urxvt-perls hunspell-de darktable gimp
pacman -S --noconfirm nemo nemo-fileroller nemo-terminal nemo-share nemo-python

#Install Themes
pacman -S --noconfirm lxappearance-gtk3 arc-gtk-theme arc-icon-theme archlinux-wallpaper

#Install fonts
pacman -S --noconfirm noto-fonts awesome-terminal-fonts

clear
echo "################"
echo "# START CONFIG #"
echo "################"
echo 
echo 

# Set hostname
clear
echo "################"
echo "# Set Hostname #"
echo "################"
echo 
read -p "Bitte Hostname eingeben: " HOST
echo $HOST >> /etc/hostname

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
clear
echo "################"
echo "# Set ROOT PW  #"
echo "################"
echo 
echo "Set Root pasword"
echo 
passwd
echo 
echo 

# Set user
clear
echo "#################"
echo "# Set new USER  #"
echo "#################"
echo 
read -p "Bitte neuen User Namen eingeben: " US
echo 
echo "Generating user $US"
echo 
useradd -m -g users -G wheel,video,audio,network -s /bin/zsh $US
echo "Set User pasword for $US"
passwd $US
echo
echo "Gebe $US ROOT rechte"
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

echo 
echo 
#start system daemons
systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
systemctl enable NetworkManager

echo 
echo 
# install grub 
grub-install --efi-directory=/boot/efi --bootloader-id=ArchVanilla
grub-mkconfig -o /boot/grub/grub.cfg

clear
echo "##################################"
echo "#### REBOOT AND LOGIN AS USER ####"
echo "#### then start script nr. 3  ####"
echo "##################################"

exit

