#!/bin/bash

###################
# INSTALL PACAGES #
###################

#Install Network pakages
pacman -S avahi networkmanager network-manager-applet nm-connection-editor ntp

#Install Audio pakages
pacman -S pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol flac volumeicon audacious

#Install Video pakages
pacman -S xf86-input-keyboard xorg-server xorg-xinit compton ffmpeg vlc mpv virtualbox-guest-dkms nvidia

#Install GUI pakages
pacman -S i3 lightdm lightdm-gtk-greeter

#Install Additional apps
pacman -S polkit-gnome xfce4-appfinder firefox firefox-i18n-de atom ranger git htop zsh zsh-completions zsh-syntax-highlighting nitrogen rofi conky dunst urxvt-perls hunspell-de

#Install Themes
pacman -S lxappearance-gtk3 arc-gtk-theme arc-icon-theme

#Install fonts
pacman -S noto-fonts awesome-terminal-fonts

################
# START CONFIG #
################

# Set hostname
read -p "Bitte Hostname eingeben: " HOST
echo $HOST >> /etc/hostname

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
echo "Set Root pasword"
passwd

# get user name
read -p "Bitte neuen User Namen eingeben: " US
# add neu user
echo "Generating user $US"
useradd -m -g users -G wheel,video,audio,network -s /bin/zsh $US
echo "Set User pasword for $US"
#add pasword for new user
passwd $US
# Enable WHEEL group for user
 echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#start system daemons
systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
systemctl enable lightdm.service 
systemctl enable NetworkManager

# install grub 
grub-install --efi-directory=/boot/efi --bootloader-id=ArchVanilla
grub-mkconfig -o /boot/grub/grub.cfg

echo ##################################
echo #### REBOOT AND LOGIN AS USER ####
echo #### then start script nr. 3  ####
echo ##################################

exit

