#!/bin/bash

# Grafiktreiber installation
clear
echo
echo "############################################"
echo "#"
echo "# 1. virtualbox"
echo "# 2. Nvidia"
echo "# 3. ATI (xf86-video-ati basis Treiber)"
echo "# 4. Intel (xf86-video-intel basis Treiber)"
echo "# 5. VESA (xf86-video-vesa basis Treiber für den Notfall)"
echo "#"
echo "#"
echo "#    Bitte wählen Sie ihren Grafiktreiber (1-5)"
echo "#"
read -p "#  >> " GR
echo
case $GR in
  1 )
    pacman -S --noconfirm virtualbox-guest-dkms
    ;;
  2 )
    pacman -S --noconfirm nvidia
    ;;
  3 )
    pacman -S --noconfirm xf86-video-ati
    ;;
  4 )
    pacman -S --noconfirm xf86-video-intel
    ;;
  5)
    pacman -S --noconfirm xf86-video-vesa
    ;;
  * )
    echo "ungültige eingabe"
    exit
esac

# GUI installation
clear
echo
echo "############################################"
echo "#"
echo "# 1. i3"
echo "# 2. Xfce"
echo "# 3. Mate"
echo "# 4. KDE-Plasma"
echo "# 5. Gnome"
echo "# 6. Deepin"
echo "# 7. Keine Gui"
echo "#"
echo "#"
echo "     Bitte wählen Sie ihren Desktop (1-7)"
echo "#"
read -p "#  >> " GUI
echo
case $GUI in
  1 )
    pacman -S --noconfirm i3
    ;;
  2 )
    pacman -S --noconfirm xfce4 xfce4-goodies
    ;;
  3 )
    pacman -S --noconfirm mate mate-extra
    ;;
  4 )
    pacman -S --noconfirm plasma
    ;;
  5)
    pacman -S --noconfirm gnome gnome-extra
    ;;
  6)
    pacman -S --noconfirm deepin deepin-extra
    ;;
  7)
    ;;
  * )
    echo "ungültige eingabe"
    exit
esac

# INSTALL PACAGES
clear
echo "############################################"
echo "# INSTALL PACAGES #"
echo "#"
echo
#Install GUI pakages
pacman -S --noconfirm lightdm lightdm-gtk-greeter xdg-user-dirs

#Install Network pakages
pacman -S --noconfirm avahi networkmanager network-manager-applet nm-connection-editor ntp

#Install Audio pakages
pacman -S --noconfirm alsa-tools alsa-utils pulseaudio pulseaudio-alsa pavucontrol flac volumeicon audacious

#Install Video pakages
pacman -S --noconfirm xorg-server xorg-xinit compton ffmpeg vlc mpv


#Install Additional apps
pacman -S --noconfirm polkit-gnome xfce4-appfinder ranger git htop nitrogen
pacman -S --noconfirm chromium atom rofi conky dunst urxvt-perls hunspell-de darktable gimp
pacman -S --noconfirm nemo nemo-fileroller rsync cool-retro-term terminology

#Install Themes
pacman -S --noconfirm lxappearance-gtk3 arc-gtk-theme arc-icon-theme archlinux-wallpaper

#Install fonts
pacman -S --noconfirm gnome-font-viewer noto-fonts awesome-terminal-fonts

# Set Root password
clear
echo "############################################"
echo "# ROOT Password festlegen"
echo "#"
echo "#"
echo "# Bitte Password für ROOT eingeben"
echo
passwd

# Set hostname
clear
echo "############################################"
echo "# HOST Erstellen "
echo "#"
echo "#"
read -p "# Bitte Hostname eingeben: " HOSTX
echo $HOSTX >> /etc/hostname

clear
echo "############################################"
echo "# Configuriere Lokale Variablen "
echo "#"
echo

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set user
clear
echo "############################################"
echo "# Neuen Benutzer erstellen  "
echo "#"
echo "#"
read -p "# Bitte neuen Benutzer Namen eingeben: " US
echo "#"
echo "# Generire Benutzer $US"
echo "#"
useradd -m -g users -G wheel,video,audio,network -s /usr/bin/fish $US
echo "# Bitte Password für $US eingeben"
passwd $US
echo "#"
echo "# Gebe $US ROOT rechte"
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#start system daemons
clear
echo "############################################"
echo "# Starte Systemdienste "
echo "#"
echo
systemctl enable acpid
systemctl enable ntpd
systemctl enable avahi-daemon
systemctl enable NetworkManager

HDD=$(</home/hdd)

clear
echo "############################################"
echo "#   Installiere GRUB   "
echo "#"
echo

if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    # install grub efi
    grub-install --efi-directory=/boot/efi --bootloader-id=Arch_$HOSTX
  else
    # install grub legacy
    grub-install /dev/$HDD
fi

grub-mkconfig -o /boot/grub/grub.cfg

clear
echo "############################################"
echo "# Bitte System neu starten und als normaler Benutzer anmelden"
echo "# Nach dem Anmelden Skript 3 starten."
echo "#"
read -p "# Drücken Sie Enter zum fortfahren"

exit
