#!/bin/bash

echo "###################"
echo "# INSTALL PACAGES #"
echo "###################"
echo 
echo 

#Install Network pakages
pacman -S --noconfirm avahi networkmanager network-manager-applet nm-connection-editor ntp

#Install Audio pakages
pacman -S --noconfirm pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol flac volumeicon audacious

#Install Video pakages
pacman -S --noconfirm xf86-input-keyboard xorg-server xorg-xinit compton ffmpeg vlc mpv virtualbox-guest-dkms nvidia

#Install GUI pakages
pacman -S --noconfirm i3blocks i3lock i3status lightdm lightdm-gtk-greeter

#Install Additional apps
pacman -S --noconfirm polkit-gnome xfce4-appfinder ranger git htop zsh zsh-completions zsh-syntax-highlighting nitrogen
pacman -S --noconfirm firefox firefox-i18n-de atom rofi conky dunst urxvt-perls hunspell-de darktable gimp
pacman -S --noconfirm nemo nemo-fileroller nemo-terminal nemo-share nemo-python

#Install Themes
pacman -S --noconfirm lxappearance-gtk3 arc-gtk-theme arc-icon-theme

#Install fonts
pacman -S --noconfirm noto-fonts awesome-terminal-fonts

echo "################"
echo "# START CONFIG #"
echo "################"
echo 
echo 

# Set hostname
read -p "Bitte Hostname eingeben: " HOST
echo $HOST >> /etc/hostname

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
echo "Set Root pasword"
echo 
passwd
echo 
echo 

# get user name
read -p "Bitte neuen User Namen eingeben: " US
echo 
# add neu user
echo "Generating user $US"
echo 
useradd -m -g users -G wheel,video,audio,network -s /bin/zsh $US
echo "Set User pasword for $US"
#add pasword for new user
passwd $US
# Enable WHEEL group for user
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

echo 
echo 
#start system daemons
systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
systemctl enable lightdm.service 
systemctl enable NetworkManager

echo 
echo 
# install grub 
grub-install --efi-directory=/boot/efi --bootloader-id=ArchVanilla
grub-mkconfig -o /boot/grub/grub.cfg

echo "##################################"
echo "#### REBOOT AND LOGIN AS USER ####"
echo "#### then start script nr. 3  ####"
echo "##################################"

exit

