#!/bin/bash

# Set hostname
read -p "Bitte Hostname eingeben: " HOST
echo $HOST >> /etc/hostname

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
echo "Set Root pasword"
passwd

# get user name
read -p "Bitte neuen User Namen eingeben: " US
# add neu user
echo "Generating user $US"
useradd -m -g users -G wheel,video,audio,network -s /bin/zsh $US
echo "Set User pasword for $US"
#add pasword for new user
passwd $US
# Enable WHEEL group for user
 echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#start system daemons
systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
systemctl enable lightdm.service 
systemctl enable NetworkManager

# install grub 
grub-install --efi-directory=/boot/efi --bootloader-id=ArchVanilla
grub-mkconfig -o /boot/grub/grub.cfg

# set global keyboard layout
localectl --no-convert set-x11-keymap de

reboot

