#!/bin/bash

# Set hostname
read -p "Bitte Hostname eingeben: " HOST
echo $HOST >> /etc/hostname

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LC_COLLATE=C >> /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1 > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# Set Time
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
echo "Set Root pasword"
passwd

# Set new user
read -p "Bitte neuen User Namen eingeben: " US
echo "Generate new User"
useradd -m -g users -G wheel,video,audio -s /bin/bash $US
echo "Set User pasword"
passwd $US
# Enable WHEEL group for ROOT
 echo %wheel ALL=(ALL) ALL >> /etc/sudoers

systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
# systemctl enable cronie 
systemctl enable lightdm.service 
systemctl enable NetworkManager

localectl --no-convert set-x11-keymap de


# GRUB 
grub-install --efi-directory=/boot/efi --bootloader-id=grub
grub-mkconfig -o /boot/grub/grub.cfg

# efibootmgr -q -c -d /dev/sdX -p 1 -w -L "GRUB: Arch-Linux" -l '\EFI\arch_grub\grubx64.efi'











