#!/bin/bash

# Set hostname
echo 4eburDom >> /etc/hostname

# /etc/locale.conf
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LC_COLLATE=C >> /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1 > /etc/vconsole.conf

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
localectl set-locale LANG=”de_DE.UTF-8”

# Set Time
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set Root password
echo "Set Root pasword"
passwd

# Set new user
echo "Generate new User"
useradd -m -g users -G wheel,video,audio -s /bin/zsh wlad
echo "Set User pasword"
passwd wlad



# Install Gui
pacman -S xorg-server xorg-xinit lightdm lightdm-gtk-greeter acpid ntp dbus avahi 

pacman -S networkmanager network-manager-applet nm-connection-editor

pacman -S pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol xfce4-appfinder caja mate-terminal

pacman -S chromium qt5 vlc mpv audacious noto-fonts arc-gtk-theme arc-icon-theme hunspell-de compton rofi neofetch nitrogen ranger

pacman -S vim-spell-de vim-spell-en zsh-autosuggestion zsh-completions zsh-syntax-highlighting
 
pacman -S xf86-video-vesa

pacman -S i3

systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
# systemctl enable cronie 
systemctl enable lightdm.service 
systemctl enable NetworkManager
localectl set-keymap --no-convert de


# GRUB 
grub-install --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg

# efibootmgr -q -c -d /dev/sdX -p 1 -w -L "GRUB: Arch-Linux" -l '\EFI\arch_grub\grubx64.efi'
