#!/bin/bash

# set global keyboard layout
sudo localectl --no-convert set-x11-keymap de

cd ~

# install yaourt
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
makepkg -si

cd ..
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvzf yaourt.tar.gz
cd yaourt
makepkg -si

yaourt -S i3-gaps-git
yaourt -S zsh-autosuggestions
yaourt -S zsh-history-substring-search-git
yaourt -S pamac-aur 
yaourt -S pamac-tray-appindicator 
yaourt -S neofetch-git 
yaourt -S imagewriter-git


# install i3 configs

cd ~
git clone https://github.com/dikiy4eburator/i3-config.git ~/.config/i3

cd ~/.config/i3/urxvt
ln .Xdefaults ~/.Xdefaults

cd ~/.config/i3/zsh
ln .zshrc ~/.zshrc

sudo cp ~/.config/i3/font/square.ttf /usr/share/fonts/TTF/square.ttf
