#!/bin/bash

cd ~

# install yaourt
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
makepkg -si

cd ..
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvzf yaourt.tar.gz
cd yaourt
makepkg -si

yaourt -S --noconfirm i3-gaps-git
yaourt -S --noconfirm zsh-autosuggestions
yaourt -S --noconfirm zsh-history-substring-search-git
yaourt -S --noconfirm pamac-aur 
yaourt -S --noconfirm pamac-tray-appindicator 
yaourt -S --noconfirm neofetch-git 
yaourt -S --noconfirm imagewriter-git


# install i3 configs

cd ~
git clone https://github.com/dikiy4eburator/i3-config.git ~/.config/i3

cd ~/.config/i3/urxvt
ln -f .Xdefaults ~/.Xdefaults

cd ~/.config/i3/zsh
ln -f .zshrc ~/.zshrc

sudo cp ~/.config/i3/font/square.ttf /usr/share/fonts/TTF/square.ttf

# set global keyboard layout
sudo localectl --no-convert set-x11-keymap de
