#!/bin/bash

pacman -S xorg-server xorg-xinit lightdm lightdm-gtk-greeter acpid ntp dbus avahi 

pacman -S networkmanager network-manager-applet nm-connection-editor

pacman -S pulseaudio alsa-tools alsa-utils pulseaudio-alsa pavucontrol xfce4-appfinder caja mate-terminal

pacman -S chromium qt5 vlc mpv audacious noto-fonts arc-gtk-theme arc-icon-theme hunspell-de compton rofi neofetch nitrogen ranger

pacman -S vim-spell-de vim-spell-en zsh-autosuggestion zsh-completions zsh-syntax-highlighting
 
pacman -S xf86-video-vesa nvidia            # (virtualbox-guest-utils)

pacman -S i3

systemctl enable acpid
systemctl enable ntpd 
systemctl enable avahi-daemon 
systemctl enable cronie 
systemctl enable lightdm.service 
systemctl enable NetworkManager

# install yaourt

curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
makepkg -si

cd ..
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvzf yaourt.tar.gz
cd yaourt
makepkg -si
 
# exit
# REBOOT

