#!/bin/sh

# ////////////////////////////////////////////////////////////
# //////////////////    VARIABELS DEFINITION    //////////////
# ////////////////////////////////////////////////////////////

# set Variabels
BoxWhith=70
consol_X=$(tput cols)
consol_Y=$(tput lines)
BoxStartX=$(( ($consol_X - $BoxWhith)/2  ))
BoxStartY=3

working_dir=$(pwd)


# includes
source $working_dir/lib/user_ops
source $working_dir/lib/menu_generator
source $working_dir/lib/auto_partition
source $working_dir/lib/manual_partition
source $working_dir/lib/MKSWAP
source $working_dir/lib/install_desktop




# /////////////////////////////////////////////////////////
# //////////////////    initial update  ///////////////////
# /////////////////////////////////////////////////////////

dialog \
--backtitle 'PrimeArch Installer' \
--title 'Wilkommen beim PrimeArch Installer' \
--begin $BoxStartY $BoxStartX \
--msgbox '\nEs wird zuerst ein vollständiges Systemupdate durchgeführt' 7 $BoxWhith

echo key update:
echo ------------------------------
pacman-key --refresh-key

echo System update:
echo ------------------------------
pacman -Syyu





# /////////////////////////////////////////////////////////////
# //////////////////    START INSTALATION   ///////////////////
# /////////////////////////////////////////////////////////////

# Welkom Screan
#===============================================================================
dialog \
--backtitle 'PrimeArch Installer' \
--title 'Wilkommen beim PrimeArch Installer' \
--begin $BoxStartY $BoxStartX \
--msgbox '\nUpdate abgeschlossen.\nLast den Spass beginnen \n' 8 $BoxWhith
#===============================================================================



# Partitionierung AUTO MANUEL
#===============================================================================
dialog \
--backtitle 'PrimeArch Installer' \
--title 'Partitionierung' \
--begin $BoxStartY $BoxStartX \
--yesno '\nMochten Sie eine automatiche Partitionierung durchführen? \n' 7 $BoxWhith \

if [[ $? -eq 0 ]];
	then
		f_autopartition
	else
		f_man_part
fi
#===============================================================================



# Install base pacages
#===============================================================================
pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pacages)
#===============================================================================



# Grafiktreiber installation
#===============================================================================
dialog \
--backtitle "PrimeArch" \
--begin $BoxStartY $BoxStartX \
--title 'Grafiktreiber wehlen' \
--menu "" 12 $BoxWhith 6 \
	1 virtualbox \
	2 Nvidia \
	3 ATI \
	4 Intel \
	5 Nouveau \
	0 'Keine Videotreiber' \
	2>/tmp/grafik_treiber

case $(</tmp/grafik_treiber) in

	1 )
		pacstrap /mnt virtualbox-guest-dkms virtualbox-guest-utils ;;
	2 )
		pacstrap /mnt nvidia-dkms ;;
	3 )
		pacstrap /mnt xf86-video-ati ;;
	4 )
		pacstrap /mnt xf86-video-intel ;;
	5 )
		pacstrap /mnt xf86-video-nouveau ;;
	0 )
		break ;;
esac
#===============================================================================



# Desktop installation
#===============================================================================
dialog \
--backtitle "PrimeArch" \
--begin $BoxStartY $BoxStartX \
--title 'Desktop wehlen' \
--menu "" 12 $BoxWhith 6 \
	1 i3 \
	2 xfce \
	3 plasma \
	4 gnome \
	o 'keinen Desktop' \
	2>/tmp/desktop

case $(</tmp/desktop) in

	1 )
		f_install_i3 ;;
	2 )
		f_install_xfce ;;
	3 )
		f_install_plasma ;;
	4 )
		f_install_gnome ;;
	0 )
		 ;;
esac
#===============================================================================



# Generate fstab
#===============================================================================
genfstab -U -p /mnt > /mnt/etc/fstab
#===============================================================================



# Generate SWAP
#===============================================================================
f_make_swap_file
#===============================================================================



# Set hostname
#===============================================================================
dialog \
--backtitle 'PrimeArch Installer' \
--begin $BoxStartY $BoxStartX \
--title 'Hostname' \
--inputbox 'Bitte Hostnamen eingeben' 8 $BoxWhith \
2>/mnt/etc/hostname
#===============================================================================



#Set ROOT
#===============================================================================
dialog \
--backtitle 'PrimeArch Installer' \
--title 'Partitionierung' \
--begin $BoxStartY $BoxStartX \
--yesno '\nMochten das ROOT konto akivieren? \n' 7 $BoxWhith \

if [[ $? -eq 0 ]];
	then
		f_root_pw_dialog
	else
		arch-chroot /mnt /bin/bash -c "passwd -l root"
fi
#===============================================================================



# CREATE NEW USER
#===============================================================================
f_create_new_user
#===============================================================================



#GENERATE SYSTEM LOCALE
#===============================================================================
# /etc/locale.conf
echo LANG=de_DE.UTF-8 >> /mnt/etc/locale.conf
echo LANGUAGE=de_DE >> /mnt/etc/locale.conf

# /etc/vconsole.conf
echo KEYMAP=de-latin1-nodeadkeys > /mnt/etc/vconsole.conf

# Set Time
rm /mnt/etc/localtime
arch-chroot /mnt /bin/bash -c 'ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime'

# /etc/locale.gen
echo de_DE.UTF-8 UTF-8 >> /mnt/etc/locale.gen

arch-chroot /mnt /bin/bash -c locale-gen
#===============================================================================



# COPY CONFIG FILES
#===============================================================================

# USER FILES --------------------

# Clone i3-config
if [[ -f "/mnt/bin/i3" ]];
  then
    git clone https://github.com/dikiy4eburator/i3-config.git /mnt/home/$(</tmp/user_name)/.config/i3

  else
    echo ""
fi

# APP configs
cp -r -v $working_dir/lib/configs/* /mnt/home/$(</tmp/user_name)/.config/
#--------------------------------



#SYSTEM FILES -------------------

#keyboard Conf
mv -f $working_dir/lib/xorg.conf.d/00-keyboard.conf /mnt/etc/X11/xorg.conf.d/00-keyboard.conf

#keyboard Conf
mv -f $working_dir/lib/lightdm-config/lightdm-gtk-greeter.conf /mnt/etc/lightdm/lightdm-gtk-greeter.conf
#--------------------------------

#===============================================================================



# INSTALL COSMETIC ADONS
#===============================================================================
mv $working_dir/lib/Addons /mnt/home/$(</tmp/user_name)/Addons
arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) sh /home/$(</tmp/user_name)/Addons"
rm /mnt/home/$(</tmp/user_name)/Addons
#===============================================================================



# FIX USER HOME OWNERSHIP
#===============================================================================
arch-chroot /mnt /bin/bash -c "chown -R $(</tmp/user_name):users /home/$(</tmp/user_name)"
arch-chroot /mnt /bin/bash -c "chmod -R 0700 /home/$(</tmp/user_name)"
#===============================================================================



#GRUB INSTALLATION
#===============================================================================
if [[ -d "/sys/firmware/efi/efivars" ]];
	then
		# install grub efi
		arch-chroot /mnt /bin/bash -c "grub-install --efi-directory=/boot/efi --bootloader-id=Arch_$(</mnt/etc/hostname)"
	else
		# install grub legacy
		arch-chroot /mnt /bin/bash -c "grub-install /dev/$(</tmp/hdd_name)"
fi

arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
#===============================================================================



# START DAEMONS
#===============================================================================
#start system daemons
arch-chroot /mnt /bin/bash -c "systemctl enable acpid"
arch-chroot /mnt /bin/bash -c "systemctl enable ntpd"

# network managment
arch-chroot /mnt /bin/bash -c "systemctl enable avahi-daemon"
arch-chroot /mnt /bin/bash -c "systemctl enable wpa_supplicant"
arch-chroot /mnt /bin/bash -c "systemctl enable NetworkManager"

# NFS utils
arch-chroot /mnt /bin/bash -c "systemctl enable rpcbind"

# Cronie
arch-chroot /mnt /bin/bash -c "systemctl enable cronie.service"

#lightdm
arch-chroot /mnt /bin/bash -c "systemctl enable lightdm.service"
#===============================================================================



##EXIT SCREAN
#===============================================================================
dialog \
--backtitle 'PrimeArch Installer' \
--title 'Installation abgeschlossen' \
--begin $BoxStartY $BoxStartX \
--menu "" 9 $BoxWhith 3 \
	1 Rebooten \
	2 Ausschalten \
	3 Chroot \
	2>/tmp/exit

case $(</tmp/exit) in
	1 )
		umount -a
		reboot ;;
	2 )
		umount -a
		poweroff ;;
	3 )
		arch-chroot /mnt ;;
esac
#===============================================================================



exit
