#!/bin/bash

dialog \
  --backtitle 'PrimeArch Installer' \
  --title 'Wilkommen' \
  --msgbox '

Bitte beantworten Sie einige Fragen zu der Systemconfiguration' 10 40

#---------------------------------------------------------
dialog \
  --backtitle 'PrimeArch Installer' \
  --title 'Extra HOME Partition' \
  --yesno '

Mochten Sie eine extra HOME Partition haben?' 10 40 \

  if [[ $? -eq 0 ]];
    then
      echo "ja" > /tmp/extrahome
    else
      echo "nein" > /tmp/extrahome
  fi
#--------------------------------------------------------


lsblk -o NAME,SIZE,MODEL,TYPE | grep disk > /tmp/hdlist

dialog \
  --backtitle 'PrimeArch Installer' \
  --title 'Festplatten Auswahl' \
  --radiolist '' 10 40





#--------------------------------------------------------

# ANSWER="/tmp/.aif"				    # Basic menu selections

dialog --backtitle "Desktop System" \
  --menu "Select Desktop:" 10 40 4 \
        1 Gnome \
        2 KDE \
        3 XFCE \
        2>/tmp/desktop


case $(</tmp/desktop) in
    1 )
    echo "aa 1"
    ;;
    2 )
    echo "bb 2"
    ;;
    3 )
    echo "dd 3"
    ;;
esac
echo "extrahome: " $(</tmp/extrahome)
