#!/bin/bash




function f_gen_passwd() {
  while IFS='' read -r line || [[ -n "$line" ]]; do
    #echo "$line"
    x=$(awk -F':' '{ print $1 }' /etc/passwd)

    if [[ $x == root ]]; then
      break
    else
      echo "$line"
    fi

done < /etc/passwd
}

#function g_gen_shadow(parameter) {
  #statements
#}

f_gen_passwd

# openssl passwd -1 -salt xyz  yourpass

# https://www.digitalocean.com/community/tutorials/how-to-use-passwd-and-adduser-to-manage-passwords-on-a-linux-vps

# /etc/passwa
# root:x:0:0:root:/root:/bin/bash
# daemon:x:1:1:daemon:/usr/sbin:/bin/sh
# bin:x:2:2:bin:/bin:/bin/sh
# sys:x:3:3:sys:/dev:/bin/sh

# /etc/shadow
# root:$6$mJD3Rsj4$xUa7jru6EEGTXnhwTfTT26/j8M5XiQvUl6UH32cfAWT/6W9iSI5IuIw5OOw4khwrsOHPyMwfCLyayfYiVdhAq0:15952:0:99999:7:::
