#!/bin/bash

cd /tmp

# install yaourt
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
makepkg -si

cd ..
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvzf yaourt.tar.gz
cd yaourt
makepkg -si

# Install some cosmetiks
# yaourt -S --noconfirm neofetch-git
# yaourt -S --noconfirm lightdm-webkit2-greeter
yaourt -S --noconfirm vertex-themes-git
yaourt -S --noconfirm vertex-icons-git
yaourt -S --noconfirm pamac-aur

exit
