#!/bin/bash

function f_autopartition() {
  sgdisk -o $(</tmp/hdd_name)

if [[ -d "/sys/firmware/efi/efivars" ]];
    then
      sgdisk -n 1:0:+256M -c 1:"BIOS Boot Partition" -t 1:ef00 $(</tmp/hdd_name)
      ENDSECTOR=`sgdisk -E $(</tmp/hdd_name)`
    else
      sgdisk -n 1:0:+5M -c 1:"EFI System Partition" -t 1:ef02 $(</tmp/hdd_name)
      ENDSECTOR=`sgdisk -E $(</tmp/hdd_name)`
fi

sgdisk -n 2:0:+$(</tmp/swap_size)G -c 2:"SWAP" -t 2:8200 $(</tmp/hdd_name)
ENDSECTOR=`sgdisk -E $(</tmp/hdd_name)`

case $(</tmp/extrahome)  in
  ja)
    sgdisk -n 3:0:+$(</tmp/root_size)G -c 3:"ROOT" -t 3:8300 $(</tmp/hdd_name)
    ENDSECTOR=`sgdisk -E $(</tmp/hdd_name)`
    sgdisk -n 4:0:0 -c 4:"HOME" -t 4:8300 $(</tmp/hdd_name)
    ;;

  nein)
    sgdisk - 3:0:0 -c 3:"ROOT" -t 3:8300 $(</tmp/hdd_name)
    ;;
esac
}
