#!/bin/bash

function f_autopartition() {
  sgdisk -oz /dev/$(</tmp/hdd_name)

  if [[ -d "/sys/firmware/efi/efivars" ]];
    then
      sgdisk -n 0:0:+256M -c 0:"BIOS Boot Partition" -t 0:ef00 /dev/$(</tmp/hdd_name)
    else
      sgdisk -n 0:0:+5M -c 0:"EFI System Partition" -t 0:ef02 /dev/$(</tmp/hdd_name)
  fi

  sgdisk -n 0:0:+$(</tmp/swap_size)G -c 0:"SWAP" -t 0:8200 /dev/$(</tmp/hdd_name)

  case $(</tmp/extrahome)  in
    ja)
      sgdisk -n 0:0:+$(</tmp/root_size)G -c 0:"ROOT" -t 0:8300 /dev/$(</tmp/hdd_name)
      sgdisk -n 0:0:0 -c 0:"HOME" -t 0:8300 /dev/$(</tmp/hdd_name)
      ;;
    nein)
      sgdisk - 0:0:0 -c 0:"ROOT" -t 0:8300 /dev/$(</tmp/hdd_name)
      ;;
    esac
}
