#!/bin/bash

function f_btrfs_installation() {

	# Install base pacages
	#===============================================================================
	f_pakage_install pakages_base
	f_pakage_install pakages_base_btrfs
	f_pakage_install pakages_base_network
	f_pakage_install pakages_base_video
	f_pakage_install pakages_base_audio
	f_pakage_install pakages_base_desktop
	f_pakage_install pakages_base_cosmetik
	#===============================================================================



	# GO TO NO PASSWORD MODE
	#===============================================================================
	cp -f -v /mnt/etc/sudoers /mnt/etc/sudoers.back
	echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /mnt/etc/sudoers
	#===============================================================================




	# Generate fstab
	#===============================================================================
	genfstab -U -p /mnt > /tmp/fstab
	awk '{ if($2 ~ /boot/) print }' /tmp/fstab > /tmp/fstab.new
	mv -fv /tmp/fstab.new /mnt/etc/fstab
	#===============================================================================



	# COPY system config FILES
	#===============================================================================
	mv -f -v $working_dir/lib/configs/btrfs/mkinitcpio.conf	/mnt/etc/mkinitcpio.conf
	#===============================================================================



	#GENERATE SYSTEM LOCALE
	#===============================================================================
	f_set_time

	case $(</tmp/language) in
		English )
			f_set_english_language ;;
		German )
			f_set_german_language ;;
		Russian )
			f_set_russian_language ;;
	esac

	arch-chroot /mnt /bin/bash -c locale-gen
	#===============================================================================



	# Set hostname
	#===============================================================================
	mv -f -v /tmp/hostname /mnt/etc/hostname
	#===============================================================================



	#Set ROOT
	#===============================================================================
	case $(</tmp/root_status) in
		yes )
			f_set_root_pw ;;
		no )
			arch-chroot /mnt /bin/bash -c "passwd -l root" ;;
	esac
	#===============================================================================



	# CREATE NEW USER
	#===============================================================================
	f_create_new_user
	#===============================================================================



	# INSTALL yaourt
	#===============================================================================
	f_install_yaourt
	#===============================================================================



	# Desktop installation
	#===============================================================================
	case $(</tmp/desktop) in
		i3 )
			f_install_desktop pakages_i3
			f_install_i3_cosmetics ;;
		
		xfce )
			f_install_desktop pakages_xfce4 ;;
		
		mate )
			f_install_desktop pakages_mate ;;
		
		gnome )
			f_install_desktop pakages_gnome ;;
		
		cinnamon )
			f_install_desktop pakages_cinnamon ;;
		
		"No Desktop" )
			;;
	esac
	#===============================================================================



	# Grafik driver installation
	#===============================================================================
	case $(</tmp/grafik_treiber) in
		Virtualbox )
			pacstrap /mnt virtualbox-guest-dkms virtualbox-guest-utils ;;
		
		Nvidia )
			pacstrap /mnt nvidia-dkms ;;
		
		ATI )
			pacstrap /mnt xf86-video-ati ;;
		
		Intel )
			pacstrap /mnt xf86-video-intel ;;
		
		Nouveau )
			pacstrap /mnt xf86-video-nouveau ;;
		
		"No Video driver" )
			;;
	esac
	#===============================================================================



	# INSTALL YAOURT + COSMETICS
	#===============================================================================
	f_install_yaourt_cosmetiks
	#===============================================================================



	# GO BACK TO  PASSWORD MODE
	#===============================================================================
	mv -f -v /mnt/etc/sudoers.back /mnt/etc/sudoers
	#===============================================================================



	# FIX USER HOME OWNERSHIP
	#===============================================================================
	arch-chroot /mnt /bin/bash -c "chown -R $(</tmp/user_name):users /home/$(</tmp/user_name)"
	arch-chroot /mnt /bin/bash -c "chmod -R 0700 /home/$(</tmp/user_name)"
	#===============================================================================

	arch-chroot /mnt /bin/bash -c "mkinitcpio -p linux"


	# START DAEMONS
	#===============================================================================
	#start system daemons
	arch-chroot /mnt /bin/bash -c "systemctl enable acpid"
	arch-chroot /mnt /bin/bash -c "systemctl enable ntpd"

	# network managment
	arch-chroot /mnt /bin/bash -c "systemctl enable avahi-daemon"
	arch-chroot /mnt /bin/bash -c "systemctl enable wpa_supplicant"
	arch-chroot /mnt /bin/bash -c "systemctl enable NetworkManager"
	arch-chroot /mnt /bin/bash -c "systemctl enable sshd.socket"

	# NFS utils
	arch-chroot /mnt /bin/bash -c "systemctl enable rpcbind"

	# Cronie
	arch-chroot /mnt /bin/bash -c "systemctl enable cronie.service"

	# lightdm
	arch-chroot /mnt /bin/bash -c "systemctl enable lightdm.service"
	#===============================================================================

	refind-install --usedefault /dev/$(</tmp/hdd_name)1
	refind-mkrlconf 

	##GRUB INSTALLATION
	##===============================================================================
	#if [[ -d "/sys/firmware/efi/efivars" ]];
	#	then
	#		# install grub efi
	#		arch-chroot /mnt /bin/bash -c "grub-install --efi-directory=/boot/efi --bootloader-id=Arch_$(</mnt/etc/hostname)"
	#	else
	#		# install grub legacy
	#		arch-chroot /mnt /bin/bash -c "grub-install /dev/$(</tmp/hdd_name)"
	#fi
	#
	#arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
	##===============================================================================
	





	# get uuid for btrfs partition
	#lsblk -f | grep $(</tmp/hdd_name)3 > /tmp/uuid
	#awk ' { print $3 } ' < /tmp/uuid > /tmp/uuid_2


	#arch-chroot /mnt /bin/bash -c "bootctl install --path=/boot --no-variables"

	#echo "timeout 30"		> /mnt/boot/loader/loader.conf
	#echo "default arch"		>> /mnt/boot/loader/loader.conf

	#echo "title		PrimeArch"					> /mnt/boot/loader/entries/arch.conf
	#echo "linux		/vmlinuz-linux"				>> /mnt/boot/loader/entries/arch.conf
	#echo "initrd	/initramfs-linux.img"		>> /mnt/boot/loader/entries/arch.conf
	#echo "options	root=PARTUUID="$(</tmp/uuid_2)" rw rootflags=subvol=ROOT"	>> /mnt/boot/loader/entries/arch.conf

	#efibootmgr -c -d /dev/$(</tmp/hdd_name) -p 1 -l /EFI/systemd/systemd-bootx64.efi -L "ARCH"


}
