#!/bin/bash

#AUTO PARTITION FUNKTION
#--------------------------------------------------------------------------------------------------------------------------------------
function f_autopartition() {
  sgdisk -ogz /dev/$(</tmp/hdd_name)

  if [[ -d "/sys/firmware/efi/efivars" ]];
    then
      sgdisk -n 1:0:+256M -c 1:"EFI System Partition" -t 1:ef00 /dev/$(</tmp/hdd_name)
    else
      sgdisk -n 1:0:+5M -c 1:"BIOS Boot Partition" -t 1:ef02 /dev/$(</tmp/hdd_name)
  fi

  sgdisk -n 2:0:+$(</tmp/swap_size)G -c 2:"SWAP" -t 2:8200 /dev/$(</tmp/hdd_name)

  case $(</tmp/extrahome)  in
    ja )
      sgdisk -n 3:0:+$(</tmp/root_size)G -c 3:"ROOT" -t 3:8300 /dev/$(</tmp/hdd_name)
      sgdisk -n 4:0:0 -c 4:"HOME" -t 4:8300 /dev/$(</tmp/hdd_name)
      ;;
    nein )
      sgdisk -n 3:0:0 -c 3:"ROOT" -t 3:8300 /dev/$(</tmp/hdd_name)
      ;;
    esac
}
#--------------------------------------------------------------------------------------------------------------------------------------





#HDD PATERN DEFENITION
#--------------------------------------------------------------------------------------------------------------------------------------
function f_def_hdd_patern_sata() {

  ROOT_HD="$(</tmp/hdd_name)3"
  SWAP_HD="$(</tmp/hdd_name)2"

if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    BOOT_HD="$(</tmp/hdd_name)1"
  else
    echo ""
fi

case $(</tmp/extrahome)  in
  ja )
    HOME_HD="$(</tmp/hdd_name)4"
    ;;
  nein )
    echo ""
    ;;
esac
}



function f_def_hdd_patern_nvme() {

  ROOT_HD="$(</tmp/hdd_name)p3"
  SWAP_HD="$(</tmp/hdd_name)p2"

if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    BOOT_HD="$(</tmp/hdd_name)p1"
  else
    echo ""
fi

case $(</tmp/extrahome)  in
  ja )
    HOME_HD="$(</tmp/hdd_name)p4"
    ;;
  nein )
    echo ""
    ;;
esac
}
#--------------------------------------------------------------------------------------------------------------------------------------





# FORMAT HARDDRIVES
#--------------------------------------------------------------------------------------------------------------------------------------
function f_format() {

  mkfs.ext4 /dev/$ROOT_HD
  mkswap /dev/$SWAP_HD

if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    mkfs.fat -F32 /dev/$BOOT_HD
  else
    echo ""
fi

case $(</tmp/extrahome)  in
  ja )
    mkfs.ext4 /dev/$HOME_HD
    ;;
  nein )
    echo ""
    ;;
esac
}
#--------------------------------------------------------------------------------------------------------------------------------------





# MOUNT HARDDRIVES
#--------------------------------------------------------------------------------------------------------------------------------------
function f_mount() {

  mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
  swapon /dev/$SWAP_HD

if [[ -d "/sys/firmware/efi/efivars" ]];
  then
    mkdir /mnt/boot
    mkdir /mnt/boot/efi
    mount /dev/$BOOT_HD /mnt/boot/efi
  else
    echo ""
fi

case $(</tmp/extrahome)  in
  ja )
    mkdir /mnt/home
    mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
    ;;
  nein )
    echo ""
    ;;
esac
}
#--------------------------------------------------------------------------------------------------------------------------------------





# MOUNT HARDDRIVES
#--------------------------------------------------------------------------------------------------------------------------------------

function f_gen_hdd_menu() {
  #Prepare Disklist
  lsblk -o NAME,SIZE,MODEL,TYPE | grep disk > /tmp/hdlist

  #gen hdd menu
  echo "#!/bin/bash" > /tmp/hdd_menu
  echo "BoxWhith=75" >> /tmp/hdd_menu
  echo "BoxStartX=2" >> /tmp/hdd_menu
  echo "BoxStartY=2" >> /tmp/hdd_menu
  echo 'dialog \' >> /tmp/hdd_menu
  echo '  --backtitle "PrimeArch" \' >> /tmp/hdd_menu
  echo '  --begin $BoxStartY $BoxStartX \' >> /tmp/hdd_menu
  echo '  --menu "Festplatte wählen" 15 $BoxWhith 7 \' >> /tmp/hdd_menu
  awk ' { print $1"\t", "\047"$2 "\t" $3"\047", "\\" } ' < /tmp/hdlist >> /tmp/hdd_menu
  echo "2>/tmp/hdd_name" >> /tmp/hdd_menu
}
#--------------------------------------------------------------------------------------------------------------------------------------
