#!/bin/sh

function f_install_i3() {

  pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/pakages_i3)

  # clone i3 config
  git clone https://github.com/dikiy4eburator/i3-config.git /mnt/home/$(</tmp/user_name)/.config/i3

  # copy APP configs
  cp -r -v $working_dir/lib/configs/* /mnt/home/$(</tmp/user_name)/.config/
}

function f_install_xfce() {
  pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/pakages_xfce4)
}

function f_install_plasma() {
  pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/pakages_plasma)
}

function f_install_gnome() {
  pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/pakages_gnome)
}
