#!/bin/sh

function f_pacage_install() {
  # Install base pacages
  #===============================================================================
  pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/$1)
  #===============================================================================
}


###############################################################################
###   Desktops
###############################################################################

function f_install_i3() {
  f_pacage_install pakages_i3

  # clone i3 config
  git clone https://github.com/dikiy4eburator/i3-config.git /mnt/home/$(</tmp/user_name)/.config/i3

  # copy APP configs
  cp -r -v $working_dir/lib/configs/i3/* /mnt/home/$(</tmp/user_name)/.config/

  arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) yaourt -S --noconfirm i3-gaps polybar"
}



function f_install_xfce() {
  f_pacage_install pakages_xfce4

  # copy APP configs
  cp -r -v $working_dir/lib/configs/xfce/* /mnt/home/$(</tmp/user_name)/.config/
}



function f_install_mate() {
  f_pacage_install pakages_mate

  # copy APP configs
  cp -r -v $working_dir/lib/configs/mate/* /mnt/home/$(</tmp/user_name)/.config/
}



function f_install_plasma() {
  f_pacage_install pakages_plasma
}



function f_install_gnome() {
  f_pacage_install pakages_gnome
}



################################################################################

function f_install_cosmetiks() {
  arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) yaourt -S --noconfirm pamac-aur vertex-icons-git vertex-themes neofetch lightdm-webkit2-greeter"
}
