#!/bin/sh

# //////////////////    LEGACY HDD PREP   ///////////////////////////////////////


function f_install_legacy() {
  case $(</tmp/hdd_name) in
    nvme*)
     f_defineHdPattern_nvme_legacy
      ;;

    sd*)
     f_defineHdPattern_sata_legacy
     ;;

    *)
      echo "HDD eingabe unbekant"
      exit
     ;;
  esac
f_format_legacy
f_mount_legacy
}



function f_defineHdPattern_sata_legacy() {
  case $(</tmp/extrahome) in
    ja )
      BOOT_HD="$(</tmp/hdd_name)1"
      SWAP_HD="$(</tmp/hdd_name)2"
      ROOT_HD="$(</tmp/hdd_name)3"
      HOME_HD="$(</tmp/hdd_name)4"
      ;;

    nein )
      BOOT_HD="$(</tmp/hdd_name)1"
      SWAP_HD="$(</tmp/hdd_name)2"
      ROOT_HD="$(</tmp/hdd_name)3"
      ;;
  esac
}



function f_defineHdPattern_nvme_legacy() {
  case $(</tmp/extrahome) in
    ja )
      BOOT_HD="$(</tmp/hdd_name)p1"
      SWAP_HD="$(</tmp/hdd_name)p2"
      ROOT_HD="$(</tmp/hdd_name)p3"
      HOME_HD="$(</tmp/hdd_name)p4"
      ;;

    nein )
      BOOT_HD="$(</tmp/hdd_name)p1"
      SWAP_HD="$(</tmp/hdd_name)p2"
      ROOT_HD="$(</tmp/hdd_name)p3"
      ;;
  esac
}



function f_format_legacy() {
  case $(</tmp/extrahome) in
    ja )
      # formating partitions
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      mkfs.ext4 /dev/$HOME_HD
      ;;

    nein )
      # formating partitions
      mkswap /dev/$SWAP_HD
      mkfs.ext4 /dev/$ROOT_HD
      ;;
  esac
}



function f_mount_legacy() {
  case $(</tmp/extrahome) in
    ja )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
#      mkdir /mnt/boot
#      mount /dev/$BOOT_HD /mnt/boot
      mkdir /mnt/home
      mount -o defaults,noatime,discard /dev/$HOME_HD /mnt/home
      swapon /dev/$SWAP_HD
      ;;

    nein )
      # Mounting partitions
      mount -o defaults,noatime,discard /dev/$ROOT_HD /mnt
#      mkdir /mnt/boot
#      mount /dev/$BOOT_HD /mnt/boot
      swapon /dev/$SWAP_HD
      ;;
  esac
}

#//////////////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////////////
