#!/bin/bash

# MANUAL PARTITIONING
#===============================================================================

function f_man_part() {
	dialog \
  --backtitle "PrimeArch" \
  --begin $BoxStartY $BoxStartX \
  --menu "Manuele Partitionierung" 15 $BoxWhith 4 \
  1 "Festplatte partitionieren" \
  2 "Partitionen mounten" \
  3 "Fertig" \
  2>/tmp/main_man_part

  case $(</tmp/main_man_part) in
		1 )
      f_gen_hdd_menu
      sh /tmp/hdd_menu

      # Show Partitioning info depending on boot mode
      if [[ -d "/sys/firmware/efi/efivars" ]];
     		then
     			dialog \
          --backtitle 'PrimeArch Installer' \
          --title 'Partitions Tabelle' \
          --begin $BoxStartY $BoxStartX \
          --msgbox '

          Im folgenden wird das Programm cgdisk gestartet
          Bitte erstellen Sie die folgenden Partitionen:

          1. EFI ca. 100-256 Mb ( code: ef00 )
          2. SWAP Gröse nach eigenem Ermessen ca. 4-8 Gb ( code: 8200 )

          Wenn Sie keine extra HOME Partition wollen
          Könne Sie den restlichen Speicher der ROOT Partition zweisen

          Ansonsten:
          3. ROOT ca. 20-40 Gb ( code: 8300 )
          4. HOME rest des Speichers ( code: 8300 ) ' 20 $BoxWhith

        else
          dialog \
          --backtitle 'PrimeArch Installer' \
          --title 'Partitions Tabelle' \
          --begin $BoxStartY $BoxStartX \
          --msgbox '

          Im folgenden wird das Programm cgdisk gestartet
          Bitte erstellen Sie die folgenden Partitionen:

          1. BOOT ca. 5 Mb ( code: ef02)
          2. SWAP Gröse nach eigenem Ermessen ca. 4-8 Gb ( code: 8200 )

          Wenn Sie keine extra HOME Partition wollen
          Könne Sie den restlichen Speicher der ROOT Partition zweisen

          Ansonsten:
          3. ROOT ca. 20-40 Gb ( code: 8300 )
          4. HOME rest des Speichers ( code: 8300 )' 20 $BoxWhith
      fi

      cgdisk /dev/$(</tmp/hdd_name)

      # Back to main menu
      f_man_part ;;

    2 )
      # Mount ROOT
   		case $(</tmp/root_mount)  in
     		ok )
     			;;
     		* )
     			f_mount_root ;;
   		esac

      # Mount SWAP
   		case $(</tmp/swap_mount)  in
     		ok )
     			;;
     		* )
     			f_mount_swap ;;
   		esac

      # Mount BOOT
   		if [[ -d "/sys/firmware/efi/efivars" ]];
   			then
   				case $(</tmp/boot_mount)  in
     				ok )
       				;;
    				* )
       				f_mount_boot ;;
     			esac
   			else
     			echo ""
   		fi

      # Mount HOME
			case $(</tmp/home_mount)  in
				ok )
					;;
				* )
					dialog \
					--backtitle 'PrimeArch Installer' \
					--begin $BoxStartY $BoxStartX \
					--yesno '\n Mochten Sie eine extra HOME Partition mounten? \n' 7 $BoxWhith \

					if [[ $? -eq 0 ]];
						then
							f_mount_home
						else
							echo 'ok' >> /tmp/boot_mount
							break
					fi
			esac

      # Back to main menu			
			f_man_part ;;

   	3 )
   		;;
  esac
}



function f_mount_boot() {
	f_gen_part_menu BOOT
  	sh /tmp/part_menu
  	mkfs.fat -F32 /dev/$(</tmp/part_name)
  	mkdir /mnt/boot
  	mkdir /mnt/boot/efi
  	mount /dev/$(</tmp/part_name) /mnt/boot/efi
  	echo 'ok' >> /tmp/boot_mount
}

function f_mount_swap() {
  	f_gen_part_menu SWAP
  	sh /tmp/part_menu
  	mkswap /dev/$(</tmp/part_name)
  	swapon /dev/$(</tmp/part_name)
  	echo 'ok' >> /tmp/swap_mount
}

function f_mount_root() {
  	f_gen_part_menu ROOT
  	sh /tmp/part_menu
  	mkfs.ext4 /dev/$(</tmp/part_name)
  	mount -o defaults,noatime,discard /dev/$(</tmp/part_name) /mnt
  	echo 'ok' >> /tmp/root_mount
}

function f_mount_home() {
  	f_gen_part_menu HOME
  	sh /tmp/part_menu
  	mkfs.ext4 /dev/$(</tmp/part_name)
  	mkdir /mnt/home
  	mount -o defaults,noatime,discard /dev/$(</tmp/part_name) /mnt/home
  	echo 'ok' >> /tmp/home_mount
}
#===============================================================================