#!/bin/sh

function f_normal() {


	# Partitionierung AUTO MANUEL
	#===============================================================================
	case $(</tmp/partitionierung) in
		1 )
			f_autopartition ;;
		2 )
			f_man_part ;;
	esac
	#===============================================================================



	# Install base pacages
	#===============================================================================
	f_pacage_install pakages_base
	f_pacage_install pakages_base_network
	f_pacage_install pakages_base_video
	f_pacage_install pakages_base_audio
	f_pacage_install pakages_base_desktop
	f_pacage_install pakages_base_cosmetik
	#===============================================================================



    # GO TO NO PASSWORD MODE
    #===============================================================================
    cp -f -v /mnt/etc/sudoers /mnt/etc/sudoers.back
    echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /mnt/etc/sudoers
    #===============================================================================



	# Generate fstab
	#===============================================================================
	genfstab -U -p /mnt > /mnt/etc/fstab
	#===============================================================================



	# Generate SWAP
	#===============================================================================
	f_make_swap_file
	#===============================================================================



	#GENERATE SYSTEM LOCALE
	#===============================================================================
	f_set_time

	case $(</tmp/language) in
  		1 )
  			f_english ;;
  		2 )
  			f_german ;;
  		3 )
  			f_russian ;;
	esac

	arch-chroot /mnt /bin/bash -c locale-gen
	#===============================================================================



	# Set hostname
	#===============================================================================
	mv -f -v /tmp/hostname /mnt/etc/hostname
	#===============================================================================



	#Set ROOT
	#===============================================================================
	case $(</tmp/root_status) in
			1 )
				f_set_root_pw ;;
			2 )
				arch-chroot /mnt /bin/bash -c "passwd -l root" ;;
	esac
	#===============================================================================



	# CREATE NEW USER
	#===============================================================================
	f_create_new_user
	#===============================================================================



	# INSTALL YAOURT
	#===============================================================================
	mv -f -v $working_dir/lib/funktions/yaourt.sh /mnt/home/$(</tmp/user_name)/yaourt.sh
	arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) sh /home/$(</tmp/user_name)/yaourt.sh"
	rm /mnt/home/$(</tmp/user_name)/yaourt.sh
	#===============================================================================



	# INSTALL DESKTOP
	#===============================================================================
	case $(</tmp/desktop) in

		i3 )
			f_install_i3 ;;
		xfce )
			f_install_xfce ;;
		mate )
			f_install_mate ;;
		plasma )
			f_install_plasma ;;
		gnome )
			f_install_gnome ;;
		"No Desktop" )
			;;
	esac
  	#===============================================================================



	# Grafiktreiber installation
	#===============================================================================
  	case $(</tmp/grafik_treiber) in
  		1 )
  			pacstrap /mnt virtualbox-guest-dkms virtualbox-guest-utils ;;
  		2 )
  			pacstrap /mnt nvidia-dkms ;;
  		3 )
  			pacstrap /mnt xf86-video-ati ;;
  		4 )
  			pacstrap /mnt xf86-video-intel ;;
  		5 )
  			pacstrap /mnt xf86-video-nouveau ;;
  		0 )
  			;;
  	esac
  	#===============================================================================



	# INSTALL YAOURT COAMETICS
	#===============================================================================
	f_install_cosmetiks
	mv -f -v $working_dir/lib/configs/lightdm-config/lightdm.conf /mnt/etc/lightdm/lightdm.conf
	#===============================================================================




	# GO BACK TO  PASSWORD MODE
	#===============================================================================
	mv -f -v /mnt/etc/sudoers.back /mnt/etc/sudoers
	#===============================================================================



	# FIX USER HOME OWNERSHIP
	#===============================================================================
	arch-chroot /mnt /bin/bash -c "chown -R $(</tmp/user_name):users /home/$(</tmp/user_name)"
	arch-chroot /mnt /bin/bash -c "chmod -R 0700 /home/$(</tmp/user_name)"
	#===============================================================================



	# START DAEMONS
	#===============================================================================
	#start system daemons
	arch-chroot /mnt /bin/bash -c "systemctl enable acpid"
	arch-chroot /mnt /bin/bash -c "systemctl enable ntpd"

	# network managment
	arch-chroot /mnt /bin/bash -c "systemctl enable avahi-daemon"
	arch-chroot /mnt /bin/bash -c "systemctl enable wpa_supplicant"
	arch-chroot /mnt /bin/bash -c "systemctl enable NetworkManager"
	arch-chroot /mnt /bin/bash -c "systemctl enable sshd.socket"

	# NFS utils
	arch-chroot /mnt /bin/bash -c "systemctl enable rpcbind"

	# Cronie
	arch-chroot /mnt /bin/bash -c "systemctl enable cronie.service"

	#lightdm
	arch-chroot /mnt /bin/bash -c "systemctl enable lightdm.service"
	#===============================================================================



	#GRUB INSTALLATION
	#===============================================================================
	if [[ -d "/sys/firmware/efi/efivars" ]];
		then
			# install grub efi
			arch-chroot /mnt /bin/bash -c "grub-install --efi-directory=/boot/efi --bootloader-id=Arch_$(</mnt/etc/hostname)"
		else
			# install grub legacy
			arch-chroot /mnt /bin/bash -c "grub-install /dev/$(</tmp/hdd_name)"
	fi

	arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
	#===============================================================================
	exit
}
