#!/bin/sh



function f_set_time_region() {

ls -l /usr/share/zoneinfo/ | awk '{ if($1 ~ /d/ && $9 !~ /posix/ && $9 !~ /right/ && $9 !~ /Etc/) print $9 " " ++s}' > /tmp/time_region_in

dialog \
--backtitle 'PrimeArch Installer' \
--title 'Zeiteinstellungen' \
--begin $BoxStartY $BoxStartX \
--menu "Zeit Zone wehlen" 20 $BoxWhith 20 \
  $( awk '{ print }' < /tmp/time_region_in ) \
  2>/tmp/time_region_out



ls -l /usr/share/zoneinfo/$(</tmp/time_region_out) | awk 'NR>=2{ print $9 " " ++s }' > /tmp/time_subregion_in

dialog \
--backtitle 'PrimeArch Installer' \
--title 'Zeiteinstellungen' \
--begin $BoxStartY $BoxStartX \
--menu "Stadt wehlen" 20 $BoxWhith 20 \
  $( awk '{ print }' < /tmp/time_subregion_in ) \
  2>/tmp/time_subregion_out


  dialog \
  --backtitle 'PrimeArch Installer' \
  --title 'Zeiteinstellungen' \
  --begin $BoxStartY $BoxStartX \
  --menu "Zeitformat wehlen" 10 $BoxWhith 3 \
    utc         1 \
    localtime   2 \
    2>/tmp/time_format


    f_set_timezone

}



function f_set_timezone() {
    #echo "ln -s /usr/share/zoneinfo/$(</tmp/time_region_out)/$(</tmp/time_subregion_out) /etc/localtime" > /tmp/xx
    #echo "hwclock --systohc --$(</tmp/time_format)" >> /tmp/xx
    arch-chroot /mnt /bin/bash -c "ln -s /usr/share/zoneinfo/$(</tmp/time_region_out)/$(</tmp/time_subregion_out) /etc/localtime"
    arch-chroot /mnt /bin/bash -c "hwclock --systohc --$(</tmp/time_format)"
}
