#!/bin/sh

function f_set_root_pw() {

  awk '{ if($1 !~ /root/) print }' /mnt/etc/shadow > /mnt/etc/new_shadow

  openssl passwd -1 -salt xyz  $(</tmp/root_pw) > /tmp/root_pw
  echo "root:$(</tmp/root_pw):17393::::::" >> /mnt/etc/new_shadow
  mv /mnt/etc/new_shadow /mnt/etc/shadow

  rm /tmp/root_pw
  rm /tmp/root_pw_2

}



function f_set_user_pw() {
  # Clear User Password
  awk '{ if($1 !~ /'$(</tmp/user_name)'/) print }' /mnt/etc/shadow > /mnt/etc/new_shadow

  # Set new User Password
  openssl passwd -1 -salt xyz  $(</tmp/user_pw) > /tmp/user_pw
  echo "$(</tmp/user_name):$(</tmp/user_pw):17393:0:99999:7:::" >> /mnt/etc/new_shadow
  mv /mnt/etc/new_shadow /mnt/etc/shadow

  rm /tmp/user_pw
  rm /tmp/user_pw_2

}
