#!/bin/sh
function f_zfs() {

  if [[ -d "/sys/firmware/efi/efivars" ]];
    then
      break
      echo "UEFI OK"
    else
      echo "NO UEFI MOD !!!"
      exit
  fi


#Prepare Disklist
ls -l /dev/disk/by-id/  > /tmp/hdlist

dialog \
--backtitle "PrimeArch" \
--begin $BoxStartY $BoxStartX \
--title "HDD Auswahl" \
--separate-output \
--checklist "Shoose the harddrives for the ZPool" 15 $BoxWhith 7 \
  $( awk '{ print $9 " " $11 " " "off" }' < /tmp/hdlist) \
2>/tmp/hdd_name


sgdisk -Z /dev/$(</tmp/hdd_name)
sgdisk -g /dev/$(</tmp/hdd_name)
sgdisk -o /dev/$(</tmp/hdd_name)

sgdisk -n 1:0:+256M -c 1:"EFI" -t 1:ef00 /dev/$(</tmp/hdd_name)
sgdisk -n 2:0:0 -c 2:"ROOT" -t 2:eb00 /dev/$(</tmp/hdd_name)

#zpool create -O atime=off -O canmount=off -O compression=lz4 -O normalization=formD zpool $(</tmp/hdd_name)

exit

}
