#!/bin/sh

function f_pacage_install() {
	# Install base pacages
	#===============================================================================
	pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/$1)
	#===============================================================================
}



function f_install_cosmetiks() {

	while read line
	do
		if [[ `expr "$line" : ".*[!@#\$%^\&*()_+].*"` -gt 0 ]];
			then
				:
			else
				arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) yaourt -S --noconfirm $line"
			fi

	done < $working_dir/lib/pakages/pakages_yaourt

}



###############################################################################
###   Desktops
###############################################################################

function f_install_i3() {
	f_pacage_install pakages_i3

	# copy APP configs
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config/
}



function f_install_xfce() {
	f_pacage_install pakages_xfce4

	# copy APP configs
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config/
}



function f_install_mate() {
	f_pacage_install pakages_mate

	# copy APP configs
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config/
}



function f_install_plasma() {
	f_pacage_install pakages_plasma

	# copy APP configs
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config/
}



function f_install_gnome() {
	f_pacage_install pakages_gnome

	# copy APP configs
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config/
}



################################################################################
