#!/bin/bash

###############################################################################
###   Pacages
###############################################################################

function f_pakage_install() {
	# Install base pacages
	#===============================================================================
	pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/$1)
	#===============================================================================
}



function f_install_cosmetiks() {

	while read line
		do
			if [[ `expr "$line" : ".*[!@#\$%^\&*()_+].*"` -gt 0 ]];
				then
					:
				else
					arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) yaourt -S --noconfirm $line"
			fi
	done < $working_dir/lib/pakages/pakages_yaourt
}



###############################################################################
###   Desktops
###############################################################################

function f_install_desktop() {
	f_pakage_install $1

	# copy APP configs
	mkdir /mnt/home/$(</tmp/user_name)/.config
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config
}


function f_install_i3() {
	# clone i3 config
	git clone https://github.com/dikiy4eburator/i3-config.git /mnt/home/$(</tmp/user_name)/.config/i3

	f_pacage_install pakages_i3
	
	arch-chroot /mnt /bin/bash -c "sudo -u $(</tmp/user_name) yaourt -S --noconfirm polybar"

	# copy APP configs
	cp -r -v $working_dir/lib/configs/app_configs/* /mnt/home/$(</tmp/user_name)/.config
}
################################################################################
