#!/bin/bash

# DYNAMIC MENU GENERATION
#===============================================================================

function f_gen_hdd_menu() {

	#Prepare Disklist
	lsblk -o NAME,SIZE,MODEL,TYPE | grep disk > /tmp/hdlist

	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "HDD Auswahl" \
	--menu "Shoose the harddrive for the installation" 15 $BoxWhith 7 \
		$(awk ' { print $1"\t"$2 } ' < /tmp/hdlist) \
	2>/tmp/hdd_name
}



function f_gen_part_menu() {

	#Prepare Partitionlist
	lsblk -l -o NAME,SIZE,MODEL,TYPE | grep part > /tmp/partlist

	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "Shoose the partition" \
	--menu "Shoose the partition for "$1 15 $BoxWhith 7 \
		$(awk ' { print $1"\t"$2 } ' < /tmp/partlist) \
	2>/tmp/part_name
}
#===============================================================================
