#!/bin/bash

function f_make_swap_file() {
	
	dd if=/dev/zero of=/mnt/SWAP bs=1M count=$(</tmp/swap_size) status=progress
	arch-chroot /mnt /bin/bash -c "mkswap /SWAP"
	arch-chroot /mnt /bin/bash -c "chmod 600 /SWAP"

	echo '# SWAP FILE' >> /mnt/etc/fstab
	echo '/SWAP			none      	swap      	defaults  	0 0' >> /mnt/etc/fstab
}
