#!/bin/sh

function f_set_time() {
    arch-chroot /mnt /bin/bash -c "ln -sf /usr/share/zoneinfo/$(</tmp/time_region_out)/$(</tmp/time_subregion_out) /etc/localtime"
    arch-chroot /mnt /bin/bash -c "hwclock --systohc --$(</tmp/time_format)"
}
